server:
  servlet:
    encoding:
      force-response: true

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kakao?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://db-rds-river.cn6oq0g93zz1.ap-northeast-2.rds.amazonaws.com:3306/testdb?useSSL=false
    username: root
    password: root
#    username: admin
#    password: rootroot

jwt:
  token:
    secret: "secretKey"
