server:
  servlet:
    encoding:
      force-response: true

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database:
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password:

jwt:
  token:
    secret:
      "secretKey"
